server:
  port: 8989
  jsp-servlet:
    init-parameters:
      development: true
  context-path: /cmfz
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-file-size: 500Mb
      max-request-size: 500Mb
mybatis:
  type-aliases-package: com.baizhi.entity